CONFIG_GPIO=y
CONFIG_SPI=y

# Raw Display Subsystem
CONFIG_DISPLAY=y
CONFIG_SSD1306=y

# Minimal Libc (Saves tons of Flash)
CONFIG_MINIMAL_LIBC=y

# Sensor Subsystem & HX711
CONFIG_SENSOR=y
CONFIG_HX711=y
CONFIG_HX711_ENABLE_EMA_FILTER=n
CONFIG_HX711_ENABLE_MEDIAN_FILTER=y
CONFIG_HX711_MEDIAN_FILTER_WINDOW_SIZE=3

# --- THE FIX: Disable Console to free up pins PA9 and PA10! ---
CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n

# Aggressive Size Optimizations
CONFIG_SIZE_OPTIMIZATIONS=y

# Multithreading Optimization 
CONFIG_MAIN_STACK_SIZE=1024
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024